### ISSUE TITLE
Player can access the Profile Menu

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#11]
Blocked by: #13 

## Description

When in the evidence menu, the player should be able to show the profile menu by pressing the 'c' button (by default). The profile menu works exactly the same as the evidence menu does, but with profiles instead of evidence. (Look at #13)
The profiles get added over the course of the game, and every unity scene should be able to have a list of default profiles that are already added. Whenever a new character is introduced, it gets added to the profile menu.

## Dev Guide

- Profiles are the same scriptable objects as actors are. Please use those instead of making new scriptable objects.
- Try to re-use most of the code the evidence uses. Maybe use a shared base class, or an interface?

## Acceptance Criteria

This story will be finished when the sample scene for the evidence is extended with the profile menu, which can be shown by pressing 'c' while in the evidence menu. It should have 9 profiles to show.

**Comment by Elementalist333** [comment]
We are waiting on art assets, but since they will be based on existing AA sprite frameworks to maintain parody feel, we should use those sprites for now and develop based off them. There might be adjustments on precise button/menu position, but that should be the only variance. Moving to actionable
