### ISSUE TITLE
Move test narrative scripts out of resources folder

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#118]
## Description
All test narrative scripts should be moved to their own folder, outside of the "Resources" folder. This is because everything in the resources folder is included in the final build of the game and we do not want to include the test scripts.

## Acceptance Criteria
This story will be finished when all the test scripts have been moved to their own folder, outside of the "Resources" folder.

**Comment by ViMaSter** [comment]
I seem to have missed this ticket when I created https://github.com/Studio-Lovelies/GG-JointJustice-Unity/issues/173. 👀 Added it there so all the cleanup Issues are linked.
