### ISSUE TITLE
[BUG] "None" and "Unknown" actors not recognised

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#128]
## Describe the bug
With changes made in #103, the None and Unknown actors no longer work.

## Steps To Reproduce
Find a script with the actions &ACTOR:None or &ACTOR:Unknown and see how they produce an error.

## Expected behavior
&ACTOR:None should hide the namebox, and &ACTOR:Unknown should set the namebox text to ???

## Additional context
Maybe best to add these as edge cases to the ActorController (i.e. if (actor == "None")).
This would avoid having to add "None" and "Unknown" actors to the actor list scriptable object.

**Comment by notexplosive** [comment]
What is the namebox color for "Unknown"? Is it always the same or is it the color of the associated actor? Maybe there should be a new `&SPEAK` command like `&SPEAK_UNKOWN:Tutorial_Boy` which means: "Tutorial boy is speaking, but the player doesn't know that" so we get all of Tutorial Boy's metadata (his dialogue chirp, namebox color, etc) _except_ his name.

**Comment by PhoebeMitchell** [comment]
In the Lua build it appears to use the same colour as Dan, as seen when Jory is introduced, and when Tutorial Boy is introduced. This could be because Dan is the last person to speak in both of those instances but after Brent speaks it is still blue. Reference:
https://youtu.be/Skop4WFElhE?t=977
Maybe best to ask the designers. I would agree it would make sense to have it be the same colour as the associated actor.

**Comment by notexplosive** [comment]
![image](https://user-images.githubusercontent.com/6920005/147788347-717133ba-b219-4cac-9497-53d63432383d.png)
Designers sound on-board with the box being the color of the speaker
