### ISSUE TITLE
Player can access the Evidence Menu

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#13]
Blocked by: https://github.com/Studio-Lovelies/GG-JointJustice-Unity/issues/8
Art assets: Make some programmer art for now, or use what we have. We can change it later

## Description

When pressing the 'z' button (by default), the evidence menu should be opened. In here, it should show all currently acquired evidence. When hovering over any evidence, it should show a description of said evidence. 

The player should be able to show the current highlighted evidence to the court by pressing enter (by default).

The menu should have an 10x1 (or check what works based on resolution) grid to show any acquired evidence. If the amount of evidence is too much to show on one page, allow the player to scroll to other pages to show the other evidence.

For mouse controls, hovering your mouse over evidence is considered hovering over, and clicking any evidence is considered showing it to the court.

A developer should be able to create a list of pre-defined evidence that the current Unity Scene should have.

Also, a script action should be added which opens the evidence menu and doesn't allow closing until you choose an evidence to present to the court.

## Dev Guide

- Pieces of evidence should be scriptable objects containing a description and an image to show.
- Some pieces of evidence change description throughout the game. Make these changed pieces of evidence different pieces of evidence, and just swap them out. (maybe link them internally to be detected as the same evidence so the system automatically swaps them?)
- Make presenting evidence a unity event exposed to the editor for now, we will hook something up to it later
- Probably a good idea to add a script to each piece of evidence in the UI which can contain a scriptable object evidence piece.

## Acceptance Criteria

This story will be finished when an example scene is made where the evidence menu can be opened and navigated with at least 9 pieces of evidence (fake ones can be made for testing). Adding evidence from the dialogue script should also be shown in here.

**Comment by Elementalist333** [comment]
We are waiting on art assets, but since they will be based on existing AA sprite frameworks to maintain parody feel, we should use those sprites for now and develop based off them. There might be adjustments on precise button/menu position, but that should be the only variance. Moving to actionable
