### ISSUE TITLE
[BUG] Make Ross not visible on last frame of his breakdown animation

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#133]
## Describe the bug
On Ross' animation "Breakdown" he should not be visible on the last frame, however the animation ends while he is still visible.

## Steps To Reproduce
Find a script with the action &PLAY_EMOTION:Breakdown and see how it stops on the last frame.

## Expected behavior
He should not be visible on the last frame.

## Screenshots
He gets stuck here
<img width="396" alt="Screenshot 2021-12-30 at 05 17 47" src="https://user-images.githubusercontent.com/67964179/147723638-284f00cb-b4ab-4b60-98a7-e299353434d9.png">
Should look like this
<img width="397" alt="Screenshot 2021-12-30 at 05 18 26" src="https://user-images.githubusercontent.com/67964179/147723662-2d6cb25f-b8e4-4461-b403-4b89c9f7cdf5.png">

**Comment by notexplosive** [comment]
my monkey-brain imagined easy fix for this is to add one extra frame at the end of the animation that's just transparent.
