### ISSUE TITLE
Player hears pauses in the blips to match the pauses in the text

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#14]
## Description

When a character talks, there should be spaces between the blips that correspond to the non-alphanumeric characters.

`Hey I'm grump, I'm not so grump` should blip as:
`***.*.*.*****..* *.***.**.*****` (where `*` is a blip and a `.` is silence)

## Acceptance Criteria

This story will be finished when text blips are only heard when the current character is an alphanumeric.

**Comment by JuiceGrape** [comment]
Closed because of re-write.
