### ISSUE TITLE
[BUG] New Game button in main menu leads to soft lock

### ISSUE THREAD

**Issue by ViMaSter** [Studio-Lovelies/GG-JointJustice-Unity#143]
## Describe the bug
Attempting to start a new game via the main menu, the game gets stuck looping an animation of the Arin sprite.

## Steps To Reproduce
- Download the latest available build of the game
- Run the game normally
- Select `New Game` in the main menu
- Notice the [soft lock](https://en.wiktionary.org/wiki/softlock)

## Expected behavior
The first episode (or earliest narrative script available; the Ross cinematic at time of writing) is run

## Screenshots
![image](https://user-images.githubusercontent.com/1689033/147863687-76418b3b-8470-498d-bf8c-0527187aaaa0.png)

(if applicable)

## Additional context
- [Discovered](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/pull/137#discussion_r777130439) by @ViMaSter testing #137 
- Version: bb982c8ee521eb7611d9adec0f09c3d69d3c2db8

**Comment by PhoebeMitchell** [comment]
The new game button should lead to a scene that plays the intro script (ross stealing the dinos). Currently "TestInk" has the intro, however this is changed in [the narrative scripts branch](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/tree/feature/turnabout-1-narrative-scripts). Also maybe wait until a method of playing scenes has been agreed upon (generic scene for all scripts, or one scene per script).

**Comment by ViMaSter** [comment]
The "New Game" button now opens the Ross cross-examination scene, which allows the main menu to be opened and the game to be properly quit.

**Comment by notexplosive** [comment]
![image](https://user-images.githubusercontent.com/6920005/159617277-6edce697-5832-4958-b1d9-b9dfa913e899.png)
mfw I softlock
