### ISSUE TITLE
ActorSlots of scenes are referenced by name and use position of GameObject of Actor

### ISSUE THREAD

**Issue by ViMaSter** [Studio-Lovelies/GG-JointJustice-Unity#178]
## Description

Some scenes in our games support multiple actors in different locations on screen. For this we utilize `Actor Positions`.
Right now, these are
- created inside Unity for each scene and the offset values have to be set up by hand with pixel values
  ![image](https://user-images.githubusercontent.com/1689033/152550833-f5fe0cdd-6261-4179-b85d-e027b91105d4.png)
- referenced inside `.ink`-files by their index (i.e. setting Ross as Witness in the scene of the screenshot above, would work by calling `&SET_ACTOR_POSITION:2,Ross` (as the index starts at 1 inside `.ink`-files)

## Acceptance Criteria

This story will be finished when
- manually entering a pixel offset is no longer required, as the position of the GameObject of the `Actor` of a slot is used instead
- the name of the GameObject of the `Actor` used as a slot is used instead of the "index+1":
  - `&SET_ACTOR_POSITION:2,Ross` would become `&SET_ACTOR_POSITION:Witness_Actor,Ross`

**Comment by PhoebeMitchell** [comment]
> &SET_ACTOR_POSITION:2,Ross would become &SET_ACTOR_POSITION:Witness_Actor,Ross

There was talk of taking this a step further and getting rid of the &SET_ACTOR_POSITION and &JUMP_TO_POSITION actions entirely, instead having &SCENE load the correct scene at the correct position instead. Unsure of the feasibility of this though, as the scenes would not be picked up by the automatic documentation.

At a minimum I think &PAN_TO_POSITION and &JUMP_TO_POSITION should be updated to use the actor slot name too.

**Comment by ViMaSter** [comment]
> Unsure of the feasibility of this though, as the scenes would not be picked up by the automatic documentation

Where there's a will, there's a way! : D  
Anything that's serialized into Unity assets can technically be added to the documentation generator. [It's actually already parsing `ActorData` and `Evidence`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/develop/docs_generator/XMLDocParser.cs#L52-L72) `ScriptableObject`s to generate [this section of the `constants.md`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/develop/docs/constants.md#:~:text=EvidenceAssetName,extremely%20predictable%20name.). If we decide to add more items later on, we could definitely do that.  
We could even go as far as taking the scene's background sprite and pixel offset - wherever that might be stored - and crop the background to show a "preview" of where an actor would be placed inside the [`constants.md`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/develop/docs/constants.md). Right now it would be as easy as [pulling the ActorSlots from the BGScenes prefab](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/develop/unity-ggjj/Assets/Resources/BGScenes/TMPHCourt.prefab#L299-L305), and adding a "SlotName" section to the [`constants.md`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/develop/docs/constants.md).

> There was talk of taking this a step further and getting rid of the &SET_ACTOR_POSITION and &JUMP_TO_POSITION actions entirely, instead having &SCENE load the correct scene at the correct position instead.

Ah, interesting. One question regarding that: How would we facilitate camera pans then? Right now I actually like the mental model of having "scenes" we can jump between, and "slots" inside a scene, which we can either jump or pan to, then again I'm not the one working on the final scripts at the moment and definitely open to changes.

To talk about code directly: How would the potential syntax for a scene like this, playing out between the `TMPHCourt`- and `TMPHJudge`-scene look with that limited "`&SCENE:` only"-syntax?

```
&SCENE:TMPHCourt
&JUMP_TO_POSITION:2
&SPEAK:Ross
<color="green">But then... I saw someone taking the dinos!!

&PLAY_SFX:HoldItArin
&WAIT:0.2
&PAN_TO_POSITION:1,0.5
&WAIT:0.5
&SPEAK:Arin
Who did you see?

&JUMP_TO_POSITION:2
&SPEAK:Ross
I'm getting to it, just be patient. I'm trying to build suspense for the viewers!

&JUMP_TO_POSITION:1
&SPEAK:Arin
But this isn't being broadcasted...

&JUMP_TO_POSITION:3
&SPEAK:TutorialBoy
Quick! Back to the testimony before we break the fourth wall again!

&SCENE:TMPHJudge
&SPEAK:JudgeBrent
Witness, carry on.
```

I'm all for reducing syntax if it's more intuitive to write, just asking since I have a bit of trouble visualizing it at the moment.  
Are you envisioning something like `&SCENE:TMPHCourt,Witness`, instead of `&SCENE:TMPHCourt` + `&JUMP_TO_POSITION:2`?

**Comment by PhoebeMitchell** [comment]
I was thinking &SCENE:TMPHDefense, &SCENE:TMPHWitness, and &SCENE:TMPHProsecution would all use TMPHCourt in game. They'd essentially be shorthand for &SCENE:TMPHCourt + &JUMP_TO_POSITION:1/2/3. Not sure what PAN_TO_POSITION would look like though. Maybe &PAN_TO_SCENE:TMPHDefense.

**Comment by ViMaSter** [comment]
Ah, that makes sense! The syntax is definitely shorter, I do see two problems with that however:
1. We could technically pan to **any** scene that way, but scenes can occupy the same absolute position.  
  In the example above, `TMPHJudge` and `TMPHWitness` are technically both at `0,0` (and cut between them using `&SCENE:`), so panning between them is actually not possible, but nothing would prevent writers from typing `&PAN_TO_SCENE:TMPHJudge` while we're on `TMPHWitness`.  
  It's not impossible to solve, but I actually think it's a bit more complicated to keep track of "when can we pan?" compared to the current implementation.
2. `&SCENE` (currently) also toggles visibility.
   If we decide to go for that route, we'd need to find out when `&SCENE:` would have to toggle visibility for only a single scene (`TMPHJudge` for example) and when there's multiple scenes that need to be active at the same time so we can pan between them (`TMPHWitness` also has `TMPHDefense` and `TMPHProsecution` next to it).
