### ISSUE TITLE
Tutorial Narrative Scripts

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#209]
## Description
We have narrative scripts for the tutorial case in [here](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/tree/feature/turnabout-1-narrative-scripts)

They need to be updated:
- Dialogue and cross examination scripts should be merged now we have the &MODE action to swap between dialogue and cross examination mode
- They need to be functional i.e. you can play through them with no errors
- Any commented actions need to be uncommented as they should have been implemented by now
- The LOAD_SCRIPT action needs to be added to the end of each script to load the next script
- Any underscores or spaces need to be removed from the script names

## Acceptance Criteria
This story will be finished when the narrative scripts are updated and functional.

**Comment by notexplosive** [comment]
Optimistically tagging as `no code` because all the code changes will be tracked as separate issues :)
