### ISSUE TITLE
[BUG] Ink giving ArgumentNullExceptions

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#222]
## Describe the bug
Ink has started giving exceptions in editor. I'm not sure why they occur. It's still possible to edit ink files, but means they sometimes don't get compiled when you edit them.

## Steps To Reproduce
Go to the develop branch
Enter play mode
Exit play mode
The errors should appear in the console

## Expected behavior
No errors

## Screenshots
<img width="449" alt="Screenshot 2022-03-26 at 03 04 26" src="https://user-images.githubusercontent.com/67964179/160222412-08828a9b-8739-4149-87b2-7ab1e7ab1d74.png">

**Comment by ViMaSter** [comment]
Tried reproducing this on 855b5cd85e1fc88aac28cbef7d84f258e03e4dbe, but toggling between play mode seems fine to me, all I see is the `DebugGameStarter: Running script RossCoolX` log message. Next time it happens, can you select the two error messages and post the full stack? Maybe there are a few more details about what is actually causing those issues to appear.

![image](https://user-images.githubusercontent.com/1689033/160235878-1e50652e-a91f-4bc4-99da-537bb07c5428.png)

Running the two built-in Ink actions does throw errors for me, however. Could that be related?

Editor logs for each action for me:
- [Starting the `Game` scene with `RossCoolX` as active scriot](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/files/8355169/222_play_pause.log)
- [Running `Rebuild Ink Library`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/files/8355170/222_rebuild_ink_library.log)
- [Running `Recompile Ink`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/files/8355171/222_recompile_ink.log)
- [Running `Validate Narrative Scripts`](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/files/8355172/222_validate_narrative_scripts.log)

**Comment by PhoebeMitchell** [comment]
The errors regarding Ink scripts are expected and fixable. I found the errors still occurred after fixing all errors in ink scripts.

```
Assertion failed
UnityEngine.Debug:Assert (bool)
Ink.UnityIntegration.InkFile:.ctor (UnityEditor.DefaultAsset) (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Ink Library/InkFile.cs:240)
Ink.UnityIntegration.InkLibrary:CreateOrReadUpdatedInkFiles (System.Collections.Generic.List`1<string>) (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Ink Library/InkLibrary.cs:279)
Ink.UnityIntegration.InkCompiler:CompilePendingFiles () (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Compiler/InkCompiler.cs:267)
Ink.
```

```
Ink file asset is null! Rebuild library using Assets > Rebuild Ink Library
UnityEngine.Debug:LogWarning (object)
Ink.UnityIntegration.InkFile:GetFileContents () (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Ink Library/InkFile.cs:263)
Ink.UnityIntegration.InkFile:ParseContent () (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Ink Library/InkFile.cs:271)
Ink.UnityIntegration.InkFile:.ctor (UnityEditor.DefaultAsset) (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Ink Library/InkFile.cs:243)
Ink.UnityIntegration.InkLibrary:CreateOrReadUpdatedInkFiles (System.Collections.Generic.List`1<string>) (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Ink Library/InkLibrary.cs:279)
Ink.UnityIntegration.InkCompiler:CompilePendingFiles () (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Compiler/InkCompiler.cs:267)
Ink.UnityIntegration.InkCompiler:OnPlayModeChange (UnityEditor.PlayModeStateChange) (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Compiler/InkCompiler.cs:249)
UnityEditor.EditorApplication:Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange) (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:404)
```

```
ReadUpdatedInkFiles (System.Collections.Generic.List`1[T] importedInkAssets) (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Ink Library/InkLibrary.cs:280)
Ink.UnityIntegration.InkCompiler.CompilePendingFiles () (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Compiler/InkCompiler.cs:267)
Ink.UnityIntegration.InkCompiler.OnPlayModeChange (UnityEditor.PlayModeStateChange mode) (at Library/PackageCache/com.inklestudios.ink-unity-integration@1.0.2/Editor/Core/Compiler/InkCompiler.cs:249)
UnityEditor.EditorApplication.Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange state) (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:404)
```

Recompiling then rebuilding ink will update any ink scripts I've edited, but then the errors come back after exiting play mode again.

**Comment by PhoebeMitchell** [comment]
Redownloading the repo seems to have fixed the issue for now. Thanks for confirming it was just me 👍
