### ISSUE TITLE
Player can set the screen resolution in settings

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#228]
Blocked by #227 (which will enable windowed mode). This will probably also be annoying to test just like #227 .

## Description
The player should have the ability to select their screen resolution. This would manifest in two ways:

- In fullscreen they can pick a resolution that matches their aspect ratio
- In windowed mode this would dictate the size of the window

## Acceptance Criteria

This story will be finished when the player can choose their resolution in the settings (via a dropdown menu?)

**Comment by notexplosive** [comment]
This doesn't feel super high priority. But it might be a problem for people on old 4:3 or ultra-wide displays.

**Comment by ViMaSter** [comment]
@notexplosive Think this is safe to close due to #382 (looks like I forgot to add `closes` so GH auto-closes this)? Feel free to reopen it, if I've missed anything or there's a regression.
