### ISSUE TITLE
Settings are stored (in save data)

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#231]
## Description

Up until now settings are ephemeral. You make a change to the settings and it stays preserved up until you close the game. They should stay preserved after the fact.

From our discussion about this we think it makes sense to store the settings in the save data. But I'm not prescribing that here if there's a more suitable way to store them.

## Acceptance Criteria

This story will be finished when the player can change any of their settings, close the game, reopen it, and their settings are preserved. This should be true for all settings.

**Comment by notexplosive** [comment]
Case 2 milestone because the lua build didn't have this.

**Comment by PhoebeMitchell** [comment]
Completed in #461
