### ISSUE TITLE
[BUG] SET_POSE cannot set pose for offscreen actor after that actor is used in another scene

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#233]
## Describe the bug
Arin appears in two BGScenes during trials in case1: TMPHCourt and Anime.
If Arin appears in Anime, then a warning will occur claiming the animator is on an inactive gameobject when `&SET_POSE:Point,Arin` in TMPHCourt

## Steps To Reproduce
Create an Ink script containing the following:

```
&SCENE:TMPHCourt
&SET_ACTOR_POSITION:1,Arin
&JUMP_TO_POSITION:2
&SCENE:Anime
&ACTOR:Arin
Example text
&SCENE:TMPHCourt
&SET_POSE:Point,Arin
```

## Expected behavior
The above script should be playable without warnings, and the actor should be able have poses set from off screen.

## Additional context
Current workaround: Call `&SET_ACTOR_POSITION:1,Arin` again after the Anime scene ends and things works as expected.
Would be nice if that wasn't necessary though.

**Comment by notexplosive** [comment]
I have a... fix? It's kind of a layer-cake of problems and I only fix the surface-most layer.
