### ISSUE TITLE
Figure out how to preserve evidence from one scene into the next

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#243]
## Description

There are two things I want:

**If I'm transitioning from scene_1.ink to scene_2.ink** I want the game to remember evidence/court record I obtained from scene1 as I enter scene2. I don't want scene_2 to need to re-add all the things I got in scene_1 (that's a technical debt timebomb).

BUT! at the same time...

**If I'm loading a scene_2.ink ad-hoc from the editor** I _still_ want it to know what evidence I obtained in scene_1.

## Acceptance Criteria

This story will be finished when evidence is preserved from scene to scene without duplicating AND a developer can still load any arbitrary scene and have the correct evidence.

**Comment by notexplosive** [comment]
Low tech solution: If a script requires you to PRESENT and item, and you don't have it, it gets silently added to evidence at the start of the script (or maybe right when the PRESENT executes)

Say you need to `PRESENT` the dinos in `scene_5`, you got the dinos added to the court record in `scene_3`:
- If you skip to `scene_5` via the editor you just have the dinos, but that's all you need
- If you got to `scene_5` via loading `scene_1` and advancing through the plot, you have the dinos because you picked them up in `scene_3`
- If you load `scene_4` (thus skipping the dinos but before the `PRESENT` requirement) the dinos materialize in your court record right at the start of `scene_5`, or right before the `PRESENT` itself. (whichever is easier for the developer).

Pros and cons:
- Con: The save file would need to remember what evidence you have (save data is more complex than it might otherwise need to be)
- Pro: Doesn't require a ton of changes on the current system (low cost)
- Pro: Free softlock protection!

**Comment by ViMaSter** [comment]
From a technical perspective, I see us having to decide on one of these options as a requirement to make this happen, each with its own advantages and disadvantages:

### a) For any given script, it's possible to find out the script that ran before
 - 👍 the game can "deduct" which items should be in the court record at the start of each chapter, by walking through the scripts before it until it's at the start of the game
- 👎 with the current solution of Ink Stories loading the next one (which I think we should keep), as soon as more than one script points to the same file, this is difficult to resolve (if the story diverges into two branches that get fused back together, would we add evidence from both?)
- 👎 alternatively, we would have to introduce the concept of [Story playlists](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/discussions/170#:~:text=In%20my%20mind,scripts%20to%20parse) to dictate the order by hand; this would remove the ability to drive the narrative exclusively via Ink code

### b) Each script is completely unaware of previous scripts, the game clears the court record items between chapters and each script starts by adding all items the player needs at this point
- 👍 starting a new game and progressing to the chapter in question, directly loading that chapter via the main menu, and the `DebugGameStarter` would follow the same flow
- each script starts with a bunch of `ADD_EVIDENCE`/`ADD_RECORD`-lines
  - 👎 lots of code duplication
  - 👎 the risk of outdated stories: imagine a writer removes an item from Case 4, but it's still present in the Case 5 file
    - though maybe this could be mitigated using [includes](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/15a449d56801f7db26457fdd3c00556228ec04cd/unity-ggjj/Assets/Tests/PlayModeTests/TestScripts/RossCoolX.ink#L1-L2#L1-L2) and [knots](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/blob/15a449d56801f7db26457fdd3c00556228ec04cd/unity-ggjj/Assets/Resources/InkDialogueScripts/Templates/FailureStates.ink#L2) in Ink instead of writing the entire block each time?
        ```
        === StartState ===
            = Case1-1
                &ADD_EVIDENCE:Switch
                &ADD_EVIDENCE:BentCoins
                -> Done
            = Case1-2
                &ADD_RECORD:TutorialBoy
                &ADD_EVIDENCE:StolenDinos
                -> Done
        ```

### c) The game keeps track of items inside savefiles
- items are tied to the savefile of the player, rather the stories
  - 👎 if we wanted to use the `DebugGameStarter`, we need to manually specify which items we have in our inventory
  - 👎 every time we change the items in the scripts, we also need to upgrade a user's savefile; manually

Fun fact:   
This final approach is both how [PyWright (fan-engine in python)](https://pywright.com/) and (if [this random Phoenix Wright Save File reference](https://gist.github.com/emiyl/1435ce18a6b1e0a5c2a74e15c19f4884#evidence) is to believed) even the official Ace Attorney Trilogy do it. Beginning to think I'm overlooking a clear advantage of that approach... 🤔

---

Addressing that list personally, I think I would go for **b)** for these reasons:
- **Re a):** The ability to keep the narrative flow entirely in Ink seems like a great thing; don't really want to lose that
- **Re b):** From a testing standpoint, having the players and developers go through the same flow as much as possible is a good thing.  
  If there's no context to keep track of, we can be sure, the player will not experience anything different.  
  If that means a bit of code duplication, I can live with that
- **Re c):** Updating save files each time we make any changes to previous scripts seems like a maintenance nightmare

Also, no matter which option we go with, I think having a sanity check as part of the build process would be a wise idea. It can be as simple as (somehow) finding the full list of Ink Stories a player will interact with from start to finish and validating, that at no point the player is asked to `PRESENT` an item that wasn't `ADD_EVIDENCE`/`ADD_RECORD`ed beforehand for each script.

**Comment by PhoebeMitchell** [comment]
I have two ideas and both of them are needlessly complicated :D

1. Parse the scripts before the game and make each line into its own state object which has all the information it needs to run.
2. Modify Ink to add in the evidence automatically

As for more realistic ideas I like @notexplosive's idea of checking a script to see if evidence is presented and automatically adding that evidence, and storing the evidence the player has in save data.

Personally I'm happy to stick with the specifying evidence at the start of Ink files but I can see why that would not be preferable.
