### ISSUE TITLE
Controls bar shows display value of keys

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#259]
## Description
As discussed [here](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/discussions/237) some keyboards have different layouts. Input System accounts for this, however the keys in the controls bar does not update to reflect different keyboard layouts. The controls in the controls bar should use keycodes as described in the above link, which will allow them to be updated to display correct keys.

## Acceptance Criteria
This story will be finished when the controls bar updates to show the correct controls for different keyboard layouts.

**Comment by notexplosive** [comment]
Case 2 because the lua build didn't support this.
