### ISSUE TITLE
[BUG] Errors in console after using Konami Code

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#369]
## Describe the bug
Using the Konamis code (up, up, down, down, left, right, left, right, b, a, start) on the main menu to play the baby scene causes the following error to appear in the console when attempting any further inputs.

```
IndexOutOfRangeException: Index was outside the bounds of the array.
Cheats.KonamiCodeHandler.<Awake>b__5_0 (UnityEngine.InputSystem.InputAction+CallbackContext ctx) (at Assets/Scripts/Cheats/KonamiCodeHandler.cs:29)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.InlinedArray`1[System.Action`1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at ./Library/PackageCache/com.unity.inputsystem@1.0.1/InputSystem/Utilities/DelegateHelpers.cs:51)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr) (at /home/bokken/build/output/unity/unity/Modules/Input/Private/Input.cs:120)```

Bug persists even after quitting to main menu.
```

## Steps To Reproduce
On the main menu, enter the Konami code: up, up, down, down, left, right, left, right, b, a, start.
After the baby scene has loaded, press any key e.g. directional arrows.
Notice errors in the console. One is an input system error that always appears when there's an error. The other is the error above.

## Expected behavior
No errors should appear.

**Comment by ViMaSter** [comment]
Small edit to fix the formatting on the initial post; well spotted though. 👀
