### ISSUE TITLE
[BUG] Dialogue skipping SFX & visual issue

### ISSUE THREAD

**Issue by IsaacLaquerre** [Studio-Lovelies/GG-JointJustice-Unity#372]
## Describe the bug

Holding X to skip dialogue still plays the dialogue SFX and doesn't skip to the end of the line immediately

## Steps To Reproduce

- Open any game scene with dialogue
- Hold X :)

## Expected behavior

Holding X to skip dialogue shouldn't play the dialogue SFX and should skip to the end of the line immediately

**Comment by PhoebeMitchell** [comment]
Great to have another contributor, and a really simple change!
Though I hate to be like this because it's your first PR and all, but I'm a little confused. Isn't the original implementation closer to how it worked in the Lua build?

**Comment by PhoebeMitchell** [comment]
This behaviour is different to the Lua build and I don't believe it's a requested feature from the other teams. Vote to close this and the associated PR? @ViMaSter @IsaacLaquerre

**Comment by ViMaSter** [comment]
Fine by me. 👍

**Comment by PhoebeMitchell** [comment]
Closing for now. Feel free to discuss further on Discord
