### ISSUE TITLE
[BUG] No evidence menu looks empty + exception

### ISSUE THREAD

**Issue by ViMaSter** [Studio-Lovelies/GG-JointJustice-Unity#424]
## Describe the bug

Using the in-game editor results in a NullReferenceException when opening the evidence menu before any evidence was added.

## Steps To Reproduce

- Open the [in-game editor](https://github.com/Studio-Lovelies/GG-JointJustice-Unity/wiki/Scripting-Basics-using-Inky#overview)
- Right after pressing Ctrl+R, press `Z` to open the evidence menu
- Notice an exception being thrown and the menu looking fairly barren

## Expected behavior

Either
- we should have some form of quip ready for when there's no evidence at all
- handle the NullReferenceException gracefully, if we don't ever expect to be in this state during normal gameplay

## Screenshots

<img width="1280" alt="image" src="https://github.com/Studio-Lovelies/GG-JointJustice-Unity/assets/1689033/d53f9700-31ee-451b-8379-89f495dfe33b">

## Additional context

- [Report on Sentry](https://studio-lovelies.sentry.io/issues/4966197224/)

**Comment by PhoebeMitchell** [comment]
For the record, this case was never implemented because there should always be at least one piece of evidence present, Arin's badge. However since it's possible to write a narrative script without the badge it's probably worth fixing.
