### ISSUE TITLE
Writer should be able to "stop" a music track

### ISSUE THREAD

**Issue by notexplosive** [Studio-Lovelies/GG-JointJustice-Unity#43]
## Description

I haven't run this by anyone but I think this is a feature we want. I thought about adding it to my existing audio controller work but it seemed too feature-y to add in a bugfix.

Currently you can do `PLAYSONG:aBoyAndHisTrial` to play a song, but say we want to transition into silence. How do we do that? This could be as simple as `PLAYSONG:silence` where "silence" is a magic string that the AudioController knows how to deal with. Or perhaps a `STOPSONG` command?

## Acceptance Criteria

This story will be finished when there is some command you can write in the NarrativeScript that stops the current background song from playing.

**Comment by JuiceGrape** [comment]
STOP_SONG is the chosen command, please use that
