### ISSUE TITLE
[BUG] Game cannot quit

### ISSUE THREAD

**Issue by PhoebeMitchell** [Studio-Lovelies/GG-JointJustice-Unity#457]
## Describe the bug
In a build you cannot quit the game.

## Steps To Reproduce
- Download latest release
- Start it then try and quit the game
- The screen goes black but does not quit and you can still use the main menu

## Expected behavior
The game should quit after the screen has faded to black.
You should not be able to use the main menu when this is happening (input is disabled)

**Comment by ViMaSter** [comment]
Could repro this with the macOS build from ded5b5ea030e9d7c0e5919f6fca2f2c612baf40d.

**Comment by PhoebeMitchell** [comment]
Recorded in Windows x64 v0.0.7
https://github.com/user-attachments/assets/f2713dd6-b1c9-4b30-bb06-3b3e0e3bb8cf
