### ISSUE TITLE
Make letter sound only play every nth letter

### ISSUE THREAD

**Issue by JuiceGrape** [Studio-Lovelies/GG-JointJustice-Unity#54]
## Description

When the dialogue is scrolling, the appearing letter sound is played with every letter that appears. This should only happen every nth letter though. The specific amount should be an input field in the appearing dialogue controller.
Furthermore, the sound should never be played on punctuation, and any '.' should reset the timer.

## Acceptance Criteria

This story will be finished when the above description is implemented

**Comment by notexplosive** [comment]
Note to whoever works on this: the text blip is super loud atm, we should either lower the volume of the sound in audacity or add some code to lower its volume.
