### ISSUE TITLE
Implement story handler

### ISSUE THREAD

**Issue by JuiceGrape** [Studio-Lovelies/GG-JointJustice-Unity#70]
## Description

Each unity scene can consist of multiple inky dialogue scripts. To make sure this is possible, the story controller should be implemented. It will hold a list of inky dialogue scripts to be played sequentially, with transitions between them (like fading to black or showing a zoomed out view, or no transition at all).

To make sure cross examination parts work properly, each of these scripts should also be flagged with a  DialogueControllerMode value, so the DialogueController can be set into the correct mode when loading the new inky script.

This script should also handle transitioning to the next unity scene when done.

## Dev Guide

- Make sure to use _onDialogueFinished event to continue when the current inky dialogue script is done
- SetNarrativeScript currently only takes a new inky dialogue script, so this should be extended to also take a DialogueControllerMode
- The first action in a script should be automatically called, which it currently isn't.

## Acceptance Criteria

This story will be finished when the aforementioned functionality is implemented and a first pre-trial unity scene is set up to test it all and set up some of the actual working behaviour going forward.

**Comment by Elementalist333** [comment]
Pretty sure all transitions between scripts should include some kind of visual transition as well. Most of the time it will be a fade in/out, but options for fade to white would be good, as well as speed control of the fading. It makes sense to me to incorporate that into the script transition function, but that's only my opinion.

**Comment by JuiceGrape** [comment]
Decided to leave transition in the dialogue scripts so writers have easier control over it. If it is deemed necessary in the future, transitions can be added
